name: Static checks

on: [ pull_request, push ]

jobs:
  ci-static-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: 'package.json'
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Run linters
        run: npm run lint
      - name: Run unit tests
        run: npm run test
